In [1]:
import hybrid

In [2]:
import pandas as pd
import numpy as np

new_data2=pd.read_csv('new_data2.csv')
synthetic_dataCTGAN=pd.read_csv('synthetic_dataCTGAN.csv')
real_data=pd.read_csv('german_credit_data.csv')
synthpop=pd.read_csv('synthpop_german.csv')

In [3]:
from sdv.metadata import SingleTableMetadata #this is a function that creates metadata, tries to capture the datatypes 
                                              
metadata = SingleTableMetadata()#creating an empty data table
metadata.detect_from_csv(filepath='german_credit_data.csv')

In [4]:
new_data2= new_data2.drop(new_data2.columns[[0]],axis=1)
new_data2
synthetic_dataCTGAN=synthetic_dataCTGAN.drop(synthetic_dataCTGAN.columns[[0]],axis=1)

In [5]:
new_data2

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,0<=X<200,10,critical/other existing credit,education,1789,<100,4<=X<7,4,male div/sep,none,...,car,42,bank,own,1,high qualif/self emp/mgmt,1,none,no,bad
1,0<=X<200,12,existing paid,used car,1739,>=1000,<1,1,female div/dep/mar,none,...,real estate,30,none,own,1,unskilled resident,2,none,yes,good
2,>=200,11,critical/other existing credit,furniture/equipment,568,<100,unemployed,3,female div/dep/mar,none,...,real estate,30,none,own,2,skilled,1,yes,yes,bad
3,<0,8,existing paid,furniture/equipment,1230,500<=X<1000,unemployed,4,male div/sep,guarantor,...,car,55,none,for free,1,high qualif/self emp/mgmt,1,none,no,bad
4,0<=X<200,8,critical/other existing credit,furniture/equipment,2817,no known savings,4<=X<7,1,female div/dep/mar,none,...,car,42,none,own,2,skilled,1,yes,yes,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0<=X<200,21,critical/other existing credit,furniture/equipment,1388,<100,unemployed,4,male single,none,...,no known property,49,none,own,2,skilled,1,yes,yes,good
29996,<0,13,delayed previously,business,1863,no known savings,1<=X<4,4,male single,none,...,car,32,none,own,2,skilled,2,yes,yes,bad
29997,<0,6,existing paid,radio/tv,1828,no known savings,4<=X<7,1,male single,none,...,real estate,31,bank,own,1,skilled,1,none,yes,good
29998,<0,7,delayed previously,new car,3604,500<=X<1000,>=7,1,male single,none,...,no known property,24,none,for free,1,skilled,2,none,yes,good
29999,no checking,19,existing paid,repairs,1782,no known savings,4<=X<7,1,male div/sep,guarantor,...,real estate,37,none,for free,2,unskilled resident,1,none,no,bad

In [8]:
from sdv.single_table import CTGANSynthesizer

synthesizerCTGAN = CTGANSynthesizer.load(
    'my_CTGAN_synthesizer.pkl'
)

TypeError: __randomstate_ctor() takes from 0 to 1 positional arguments but 2 were given

In [6]:
result = hybrid.hybrid(real_data, new_data2,synthetic_dataCTGAN , metadata)

First dataset quality score:

Creating report: 100%|███████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.06it/s]

Overall Quality Score: 85.47%

Properties:
Column Shapes: 89.03%
Column Pair Trends: 81.9%
Second dataset quality score:

Creating report: 100%|███████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.28it/s]

Overall Quality Score: 87.74%

Properties:
Column Shapes: 89.88%
Column Pair Trends: 85.59%
--------------First dataset report:-------------
                    Column        Metric  Quality Score
0                 duration  KSComplement       0.900233
1            credit_amount  KSComplement       0.939000
2   installment_commitment  KSComplement       0.951000
3          residence_since  KSComplement       0.927133
4                      age  KSComplement       0.977800
5         existing_credits  KSComplement       0.883900
6           num_dependents  KSComplement       0.934433
7          checking_status  TVComplement       0.859067
8           credit_history  TVComplement       0.812833
9                  purpose  TVComplement       0.803333
10          savings_status  TVComplement       0.646467
11              employment  TVComplement       0.823167
12         personal_status  TVComplement       0.914600
13           other_parties  TVComplement       0.883467
14      property_magnitude  TVComplement       0.941000
15     other_payment_plans  TVComplement       0.919667
16                 housing  TVComplement       0.863600
17                     job  TVComplement       0.905000
18           own_telephone  TVComplement       0.963500
19          foreign_worker  TVComplement       0.911667
20                   class  TVComplement       0.936167
--------------Second dataset report:------------
                    Column        Metric  Quality Score
0                 duration  KSComplement       0.866600
1            credit_amount  KSComplement       0.592633
2   installment_commitment  KSComplement       0.896733
3          residence_since  KSComplement       0.927200
4                      age  KSComplement       0.870700
5         existing_credits  KSComplement       0.779533
6           num_dependents  KSComplement       0.879267
7          checking_status  TVComplement       0.874200
8           credit_history  TVComplement       0.946100
9                  purpose  TVComplement       0.902133
10          savings_status  TVComplement       0.968933
11              employment  TVComplement       0.936400
12         personal_status  TVComplement       0.937733
13           other_parties  TVComplement       0.939400
14      property_magnitude  TVComplement       0.919867
15     other_payment_plans  TVComplement       0.979667
16                 housing  TVComplement       0.957400
17                     job  TVComplement       0.946133
18           own_telephone  TVComplement       0.869733
19          foreign_worker  TVComplement       0.995700
20                   class  TVComplement       0.888867
------------- Combined Quality score------------
                    Column        Metric  Quality Score_1  Quality Score_2
0                 duration  KSComplement         0.900233         0.866600
1            credit_amount  KSComplement         0.939000         0.592633
2   installment_commitment  KSComplement         0.951000         0.896733
3          residence_since  KSComplement         0.927133         0.927200
4                      age  KSComplement         0.977800         0.870700
5         existing_credits  KSComplement         0.883900         0.779533
6           num_dependents  KSComplement         0.934433         0.879267
7          checking_status  TVComplement         0.859067         0.874200
8           credit_history  TVComplement         0.812833         0.946100
9                  purpose  TVComplement         0.803333         0.902133
10          savings_status  TVComplement         0.646467         0.968933
11              employment  TVComplement         0.823167         0.936400
12         personal_status  TVComplement         0.914600         0.937733
13           other_parties  TVComplement         0.883467         0.939400
14      property_magnitude  TVComplement         0.941000         0.919867
15     other_payment_plans  TVComplement         0.919667         0.979667
16                 housing  TVComplement         0.863600         0.957400
17                     job  TVComplement         0.905000         0.946133
18           own_telephone  TVComplement         0.963500         0.869733
19          foreign_worker  TVComplement         0.911667         0.995700
20                   class  TVComplement         0.936167         0.888867
Name of columns for which transformation have  been used:
['duration', 'credit_amount', 'installment_commitment', 'property_magnitude', 'age', 'existing_credits', 'num_dependents', 'own_telephone', 'class']
{
    "sdtypes": {
        "checking_status": "categorical",
        "duration": "numerical",
        "credit_history": "categorical",
        "purpose": "categorical",
        "credit_amount": "numerical",
        "savings_status": "categorical",
        "employment": "categorical",
        "installment_commitment": "numerical",
        "personal_status": "categorical",
        "other_parties": "categorical",
        "residence_since": "numerical",
        "property_magnitude": "categorical",
        "age": "numerical",
        "other_payment_plans": "categorical",
        "housing": "categorical",
        "existing_credits": "numerical",
        "job": "categorical",
        "num_dependents": "numerical",
        "own_telephone": "categorical",
        "foreign_worker": "categorical",
        "class": "categorical"
    },
    "transformers": {
        "checking_status": None,
        "duration": None,
        "credit_history": None,
        "purpose": None,
        "credit_amount": None,
        "savings_status": None,
        "employment": None,
        "installment_commitment": None,
        "personal_status": None,
        "other_parties": None,
        "residence_since": None,
        "property_magnitude": LabelEncoder(),
        "age": None,
        "other_payment_plans": None,
        "housing": None,
        "existing_credits": None,
        "job": None,
        "num_dependents": None,
        "own_telephone": LabelEncoder(),
        "foreign_worker": None,
        "class": LabelEncoder()
    }
}
Details of transformers used for all variables:
{
    "sdtypes": {
        "checking_status": "categorical",
        "duration": "numerical",
        "credit_history": "categorical",
        "purpose": "categorical",
        "credit_amount": "numerical",
        "savings_status": "categorical",
        "employment": "categorical",
        "installment_commitment": "numerical",
        "personal_status": "categorical",
        "other_parties": "categorical",
        "residence_since": "numerical",
        "property_magnitude": "categorical",
        "age": "numerical",
        "other_payment_plans": "categorical",
        "housing": "categorical",
        "existing_credits": "numerical",
        "job": "categorical",
        "num_dependents": "numerical",
        "own_telephone": "categorical",
        "foreign_worker": "categorical",
        "class": "categorical"
    },
    "transformers": {
        "checking_status": None,
        "duration": None,
        "credit_history": None,
        "purpose": None,
        "credit_amount": None,
        "savings_status": None,
        "employment": None,
        "installment_commitment": None,
        "personal_status": None,
        "other_parties": None,
        "residence_since": None,
        "property_magnitude": LabelEncoder(),
        "age": None,
        "other_payment_plans": None,
        "housing": None,
        "existing_credits": None,
        "job": None,
        "num_dependents": None,
        "own_telephone": LabelEncoder(),
        "foreign_worker": None,
        "class": LabelEncoder()
    }
}
Hybrid quality score

Creating report: 100%|███████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.06s/it]

Overall Quality Score: 91.59%

Properties:
Column Shapes: 93.99%
Column Pair Trends: 89.18%
Hybrid dataset report:
                    Column        Metric  Quality Score
0                 duration  KSComplement       0.900233
1            credit_amount  KSComplement       0.939000
2   installment_commitment  KSComplement       0.951000
3          residence_since  KSComplement       0.927200
4                      age  KSComplement       0.977800
5         existing_credits  KSComplement       0.883900
6           num_dependents  KSComplement       0.934433
7          checking_status  TVComplement       0.874200
8           credit_history  TVComplement       0.946100
9                  purpose  TVComplement       0.902133
10          savings_status  TVComplement       0.968933
11              employment  TVComplement       0.936400
12         personal_status  TVComplement       0.937733
13           other_parties  TVComplement       0.939400
14      property_magnitude  TVComplement       0.941000
15     other_payment_plans  TVComplement       0.979667
16                 housing  TVComplement       0.957400
17                     job  TVComplement       0.946133
18           own_telephone  TVComplement       0.963500
19          foreign_worker  TVComplement       0.995700
20                   class  TVComplement       0.936167
 Combined Quality score
                    Column        Metric  Quality Score_1  Quality Score_2  \
0                 duration  KSComplement         0.900233         0.866600
1            credit_amount  KSComplement         0.939000         0.592633
2   installment_commitment  KSComplement         0.951000         0.896733
3          residence_since  KSComplement         0.927133         0.927200
4                      age  KSComplement         0.977800         0.870700
5         existing_credits  KSComplement         0.883900         0.779533
6           num_dependents  KSComplement         0.934433         0.879267
7          checking_status  TVComplement         0.859067         0.874200
8           credit_history  TVComplement         0.812833         0.946100
9                  purpose  TVComplement         0.803333         0.902133
10          savings_status  TVComplement         0.646467         0.968933
11              employment  TVComplement         0.823167         0.936400
12         personal_status  TVComplement         0.914600         0.937733
13           other_parties  TVComplement         0.883467         0.939400
14      property_magnitude  TVComplement         0.941000         0.919867
15     other_payment_plans  TVComplement         0.919667         0.979667
16                 housing  TVComplement         0.863600         0.957400
17                     job  TVComplement         0.905000         0.946133
18           own_telephone  TVComplement         0.963500         0.869733
19          foreign_worker  TVComplement         0.911667         0.995700
20                   class  TVComplement         0.936167         0.888867

    Quality Score_3
0          0.900233
1          0.939000
2          0.951000
3          0.927200
4          0.977800
5          0.883900
6          0.934433
7          0.874200
8          0.946100
9          0.902133
10         0.968933
11         0.936400
12         0.937733
13         0.939400
14         0.941000
15         0.979667
16         0.957400
17         0.946133
18         0.963500
19         0.995700
20         0.936167

In [7]:
result

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
27136,no checking,36,delayed previously,new car,6954,100<=X<500,>=7,4,female div/dep/mar,none,...,car,66,none,own,1,skilled,1,none,yes,good
2190,0<=X<200,13,existing paid,furniture/equipment,2147,<100,4<=X<7,4,male single,none,...,life insurance,28,bank,own,2,high qualif/self emp/mgmt,2,none,yes,bad
25654,<0,25,critical/other existing credit,radio/tv,4448,>=1000,>=7,4,male single,none,...,real estate,34,none,own,3,skilled,1,none,yes,good
70,no checking,6,critical/other existing credit,radio/tv,333,no known savings,4<=X<7,4,male single,none,...,real estate,25,none,rent,2,skilled,1,none,yes,bad
23260,<0,6,existing paid,radio/tv,1413,<100,<1,1,male single,co applicant,...,no known property,65,none,own,1,skilled,2,yes,yes,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20169,0<=X<200,9,existing paid,education,771,<100,unemployed,4,female div/dep/mar,none,...,no known property,34,bank,rent,1,skilled,2,none,yes,good
23281,<0,28,existing paid,furniture/equipment,7695,<100,1<=X<4,1,male div/sep,none,...,life insurance,26,none,own,1,skilled,1,none,yes,bad
13253,0<=X<200,30,existing paid,radio/tv,2934,no known savings,>=7,4,female div/dep/mar,none,...,no known property,24,none,own,1,skilled,1,none,yes,good
9470,0<=X<200,39,existing paid,education,7304,<100,<1,2,male mar/wid,none,...,no known property,24,bank,for free,1,unskilled resident,1,yes,yes,bad
15192,<0,8,critical/other existing credit,business,1846,<100,1<=X<4,1,male single,none,...,car,60,none,own,2,unskilled resident,1,yes,yes,good

In [8]:
synthpop

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,no checking,15,critical/other existing credit,furniture/equipment,1366,<100,>=7,2,male single,none,...,life insurance,65,none,own,2,unskilled resident,1,yes,yes,good
1,<0,9,critical/other existing credit,other,2214,<100,4<=X<7,2,male single,none,...,real estate,52,none,own,2,skilled,1,yes,yes,good
2,no checking,47,no credits/all paid,repairs,10722,<100,>=7,2,female div/dep/mar,none,...,life insurance,38,none,for free,1,skilled,2,none,yes,bad
3,<0,9,existing paid,new car,385,<100,>=7,4,male single,none,...,life insurance,51,none,own,2,skilled,1,yes,yes,good
4,>=200,24,existing paid,used car,1659,<100,1<=X<4,4,male single,none,...,life insurance,63,none,own,3,unskilled resident,1,yes,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0<=X<200,15,critical/other existing credit,furniture/equipment,674,500<=X<1000,>=7,4,male single,none,...,life insurance,52,none,own,3,skilled,1,yes,yes,good
29996,no checking,6,critical/other existing credit,furniture/equipment,1957,no known savings,1<=X<4,2,male single,none,...,life insurance,47,none,own,1,skilled,2,none,yes,good
29997,0<=X<200,6,existing paid,new car,2647,<100,4<=X<7,2,male single,none,...,real estate,28,none,rent,2,unskilled resident,2,yes,yes,good
29998,no checking,24,existing paid,radio/tv,3357,<100,<1,3,male single,none,...,life insurance,20,none,rent,2,skilled,1,yes,yes,good
29999,0<=X<200,15,critical/other existing credit,new car,1200,<100,1<=X<4,2,male single,none,...,car,28,none,own,2,high qualif/self emp/mgmt,1,none,yes,good

In [11]:
result2 = hybrid.hybrid(real_data, result,synthpop , metadata)

First dataset quality score:

Creating report: 100%|███████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.23it/s]

Overall Quality Score: 91.59%

Properties:
Column Shapes: 93.99%
Column Pair Trends: 89.18%
Second dataset quality score:

Creating report: 100%|███████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.28it/s]

Overall Quality Score: 77.19%

Properties:
Column Shapes: 81.04%
Column Pair Trends: 73.34%
--------------First dataset report:-------------
                    Column        Metric  Quality Score
0                 duration  KSComplement       0.900233
1            credit_amount  KSComplement       0.939000
2   installment_commitment  KSComplement       0.951000
3          residence_since  KSComplement       0.927200
4                      age  KSComplement       0.977800
5         existing_credits  KSComplement       0.883900
6           num_dependents  KSComplement       0.934433
7          checking_status  TVComplement       0.874200
8           credit_history  TVComplement       0.946100
9                  purpose  TVComplement       0.902133
10          savings_status  TVComplement       0.968933
11              employment  TVComplement       0.936400
12         personal_status  TVComplement       0.937733
13           other_parties  TVComplement       0.939400
14      property_magnitude  TVComplement       0.941000
15     other_payment_plans  TVComplement       0.979667
16                 housing  TVComplement       0.957400
17                     job  TVComplement       0.946133
18           own_telephone  TVComplement       0.963500
19          foreign_worker  TVComplement       0.995700
20                   class  TVComplement       0.936167
--------------Second dataset report:------------
                    Column        Metric  Quality Score
0                 duration  KSComplement       0.961133
1            credit_amount  KSComplement       0.761667
2   installment_commitment  KSComplement       0.837200
3          residence_since  KSComplement       0.603400
4                      age  KSComplement       0.456600
5         existing_credits  KSComplement       0.583233
6           num_dependents  KSComplement       0.983033
7          checking_status  TVComplement       0.998633
8           credit_history  TVComplement       0.909567
9                  purpose  TVComplement       0.744100
10          savings_status  TVComplement       0.817800
11              employment  TVComplement       0.654600
12         personal_status  TVComplement       0.859633
13           other_parties  TVComplement       0.955600
14      property_magnitude  TVComplement       0.839333
15     other_payment_plans  TVComplement       0.888667
16                 housing  TVComplement       0.820233
17                     job  TVComplement       0.677300
18           own_telephone  TVComplement       0.772900
19          foreign_worker  TVComplement       0.984567
20                   class  TVComplement       0.909800
------------- Combined Quality score------------
                    Column        Metric  Quality Score_1  Quality Score_2
0                 duration  KSComplement         0.900233         0.961133
1            credit_amount  KSComplement         0.939000         0.761667
2   installment_commitment  KSComplement         0.951000         0.837200
3          residence_since  KSComplement         0.927200         0.603400
4                      age  KSComplement         0.977800         0.456600
5         existing_credits  KSComplement         0.883900         0.583233
6           num_dependents  KSComplement         0.934433         0.983033
7          checking_status  TVComplement         0.874200         0.998633
8           credit_history  TVComplement         0.946100         0.909567
9                  purpose  TVComplement         0.902133         0.744100
10          savings_status  TVComplement         0.968933         0.817800
11              employment  TVComplement         0.936400         0.654600
12         personal_status  TVComplement         0.937733         0.859633
13           other_parties  TVComplement         0.939400         0.955600
14      property_magnitude  TVComplement         0.941000         0.839333
15     other_payment_plans  TVComplement         0.979667         0.888667
16                 housing  TVComplement         0.957400         0.820233
17                     job  TVComplement         0.946133         0.677300
18           own_telephone  TVComplement         0.963500         0.772900
19          foreign_worker  TVComplement         0.995700         0.984567
20                   class  TVComplement         0.936167         0.909800
Name of columns for which transformation have  been used:
['credit_history', 'purpose', 'credit_amount', 'savings_status', 'employment', 'installment_commitment', 'personal_status', 'residence_since', 'property_magnitude', 'age', 'other_payment_plans', 'housing', 'existing_credits', 'job', 'own_telephone', 'foreign_worker', 'class']
{
    "sdtypes": {
        "checking_status": "categorical",
        "duration": "numerical",
        "credit_history": "categorical",
        "purpose": "categorical",
        "credit_amount": "numerical",
        "savings_status": "categorical",
        "employment": "categorical",
        "installment_commitment": "numerical",
        "personal_status": "categorical",
        "other_parties": "categorical",
        "residence_since": "numerical",
        "property_magnitude": "categorical",
        "age": "numerical",
        "other_payment_plans": "categorical",
        "housing": "categorical",
        "existing_credits": "numerical",
        "job": "categorical",
        "num_dependents": "numerical",
        "own_telephone": "categorical",
        "foreign_worker": "categorical",
        "class": "categorical"
    },
    "transformers": {
        "checking_status": None,
        "duration": None,
        "credit_history": LabelEncoder(),
        "purpose": LabelEncoder(),
        "credit_amount": None,
        "savings_status": LabelEncoder(),
        "employment": LabelEncoder(),
        "installment_commitment": None,
        "personal_status": LabelEncoder(),
        "other_parties": None,
        "residence_since": None,
        "property_magnitude": LabelEncoder(),
        "age": None,
        "other_payment_plans": LabelEncoder(),
        "housing": LabelEncoder(),
        "existing_credits": None,
        "job": LabelEncoder(),
        "num_dependents": None,
        "own_telephone": LabelEncoder(),
        "foreign_worker": LabelEncoder(),
        "class": LabelEncoder()
    }
}
Details of transformers used for all variables:
{
    "sdtypes": {
        "checking_status": "categorical",
        "duration": "numerical",
        "credit_history": "categorical",
        "purpose": "categorical",
        "credit_amount": "numerical",
        "savings_status": "categorical",
        "employment": "categorical",
        "installment_commitment": "numerical",
        "personal_status": "categorical",
        "other_parties": "categorical",
        "residence_since": "numerical",
        "property_magnitude": "categorical",
        "age": "numerical",
        "other_payment_plans": "categorical",
        "housing": "categorical",
        "existing_credits": "numerical",
        "job": "categorical",
        "num_dependents": "numerical",
        "own_telephone": "categorical",
        "foreign_worker": "categorical",
        "class": "categorical"
    },
    "transformers": {
        "checking_status": None,
        "duration": None,
        "credit_history": LabelEncoder(),
        "purpose": LabelEncoder(),
        "credit_amount": None,
        "savings_status": LabelEncoder(),
        "employment": LabelEncoder(),
        "installment_commitment": None,
        "personal_status": LabelEncoder(),
        "other_parties": None,
        "residence_since": None,
        "property_magnitude": LabelEncoder(),
        "age": None,
        "other_payment_plans": LabelEncoder(),
        "housing": LabelEncoder(),
        "existing_credits": None,
        "job": LabelEncoder(),
        "num_dependents": None,
        "own_telephone": LabelEncoder(),
        "foreign_worker": LabelEncoder(),
        "class": LabelEncoder()
    }
}
Hybrid quality score

Creating report: 100%|███████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.09s/it]

Overall Quality Score: 92.86%

Properties:
Column Shapes: 95.18%
Column Pair Trends: 90.54%
Hybrid dataset report:
                    Column        Metric  Quality Score
0                 duration  KSComplement       0.961133
1            credit_amount  KSComplement       0.939000
2   installment_commitment  KSComplement       0.951000
3          residence_since  KSComplement       0.927200
4                      age  KSComplement       0.977800
5         existing_credits  KSComplement       0.883900
6           num_dependents  KSComplement       0.983033
7          checking_status  TVComplement       0.998633
8           credit_history  TVComplement       0.946100
9                  purpose  TVComplement       0.902133
10          savings_status  TVComplement       0.968933
11              employment  TVComplement       0.936400
12         personal_status  TVComplement       0.937733
13           other_parties  TVComplement       0.955600
14      property_magnitude  TVComplement       0.941000
15     other_payment_plans  TVComplement       0.979667
16                 housing  TVComplement       0.957400
17                     job  TVComplement       0.946133
18           own_telephone  TVComplement       0.963500
19          foreign_worker  TVComplement       0.995700
20                   class  TVComplement       0.936167
 Combined Quality score
                    Column        Metric  Quality Score_1  Quality Score_2  \
0                 duration  KSComplement         0.900233         0.961133
1            credit_amount  KSComplement         0.939000         0.761667
2   installment_commitment  KSComplement         0.951000         0.837200
3          residence_since  KSComplement         0.927200         0.603400
4                      age  KSComplement         0.977800         0.456600
5         existing_credits  KSComplement         0.883900         0.583233
6           num_dependents  KSComplement         0.934433         0.983033
7          checking_status  TVComplement         0.874200         0.998633
8           credit_history  TVComplement         0.946100         0.909567
9                  purpose  TVComplement         0.902133         0.744100
10          savings_status  TVComplement         0.968933         0.817800
11              employment  TVComplement         0.936400         0.654600
12         personal_status  TVComplement         0.937733         0.859633
13           other_parties  TVComplement         0.939400         0.955600
14      property_magnitude  TVComplement         0.941000         0.839333
15     other_payment_plans  TVComplement         0.979667         0.888667
16                 housing  TVComplement         0.957400         0.820233
17                     job  TVComplement         0.946133         0.677300
18           own_telephone  TVComplement         0.963500         0.772900
19          foreign_worker  TVComplement         0.995700         0.984567
20                   class  TVComplement         0.936167         0.909800

    Quality Score_3
0          0.961133
1          0.939000
2          0.951000
3          0.927200
4          0.977800
5          0.883900
6          0.983033
7          0.998633
8          0.946100
9          0.902133
10         0.968933
11         0.936400
12         0.937733
13         0.955600
14         0.941000
15         0.979667
16         0.957400
17         0.946133
18         0.963500
19         0.995700
20         0.936167

In [12]:
from sdv.evaluation.single_table import evaluate_quality

quality_report2 = evaluate_quality(
    real_data,
    result2,
    metadata
)

Creating report: 100%|███████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.11s/it]

Overall Quality Score: 92.86%

Properties:
Column Shapes: 95.18%
Column Pair Trends: 90.54%